### PR TITLE
remove 10% minimum width from score bar

### PR DESCRIPTION
**Pull request by dsnyder-fairway**
changes are to address DWR-1251

### CODE REVIEW

**Comment by jtreuting** [comment]
is this only used in one place?  so with the new score distribution on the HTML version of the group and school/grade since the % is next to the bar, we don't need the strange gap to allow for the number to show.  so if it is 5% we can show just 5% of the bar.

if this is used anywhere else then we need to be careful like in the PDF or soemthing.

**Comment by esotrope** [comment]
it at least wont affect PDFs

> `body:not(.pdf)`

**Comment by dsnyder-fairway** [comment]
@jtreuting IAT doesn't display any graphs. I'm not sure what other projects use the SBAC global UI kit

**Comment by jtreuting** [comment]
@aaronsleeper is it cool to remove this class since we don't need the 0-10% "gap" fix with the new student score distribution section in RDW?

**Comment by aaronsleeper** [comment]
yes @jtreuting we no longer will need this class if all graphs will be updated to the new style

**Pull request merged**
